### ISSUE TITLE
Support for proofs of abscence?

### ISSUE THREAD

**Issue by seunlanlege** [paritytech/trie#147]
Does this support generating proofs for non-inclusion? kinda like the [ethereum mpt](https://github.com/ethereumjs/merkle-patricia-tree/pull/82).

Considering using this for generating IBC packet inclusion/non-inclusion proofs as per [ics-023](https://github.com/cosmos/ibc/tree/master/spec/core/ics-023-vector-commitments#proof-generation)

**Comment by cheme** [comment]
Yes, if you record a proof on a missing value, the nodes along its path included in the proof (proving there is no child at some point for the missing key).

**Comment by seunlanlege** [comment]
Yes I've confirmed this behavior, thanks @cheme
