### ISSUE TITLE
Use hashbrown instead of hashmap_core

### ISSUE THREAD

**Issue by cheme** [paritytech/trie#21]
This issue is keeping trace of the fact that we use hashmap_core for trie hashmap, but want to switch to another `no_std` implementation in the future.

Best candidate is probably hashbrown (already use in some other parity crates), but in the current state the way no_std is managed makes thing pretty awkward (would requires adding some cargo features).

So current plan is more a wait and see (hashbrown seems to be in process to be use in the rust std lib maybe wait for it before seeing how to make this switch this properly).

When switching parity-util-mem could also implement malloc_size_of for the chosen 'no_std' implementation.

**Comment by tomusdrw** [comment]
I guess we need to bump priority on this one. `hashmap_core` is now deprecated and I think it doesn't compile with latest nightly.
