### ISSUE TITLE
Create an iterator for a prefix

### ISSUE THREAD

**Issue by cheme** [paritytech/trie#32]
Substrate currently query trie nodes by prefix. 
This operation is using triedb iterator 'seek' at prefix, then calling iterator 'next' until a value does not begin with a prefix.
This is problematic in case the operation is run over a proof: the proof/witness will need it include query to this last value (which is not strictly needed).
A more compact/correct proof is doable by limiting the iteration only to the branches that contains the prefix.

This operation will simply be a variant of 'iter', likely 'iter_prefix'.

**Comment by ordian** [comment]
was it resolved by #39?

**Comment by cheme** [comment]
Yes, closing it :+1:
