### ISSUE TITLE
Deduplicate hashdb, memorydb, from parity-common

### ISSUE THREAD

**Issue by rphmeier** [paritytech/trie#5]

**Comment by cheme** [comment]
I would also like to merge those crates with the parity-common crates.
I think trie-db also need to be deduplicate (I want to run a few test with trie-root in parity-eth, and also got an alternate implementation to test).
So just to be sure, do we plan on keeping those repo here or moving them to parity-common ?

**Comment by rphmeier** [comment]
If the changes Gav made are able to be ported back to `parity-common`, then yes please!

**Comment by ordian** [comment]
Seems to be resolved by paritytech/parity-common#106 and paritytech/parity-ethereum#10314.
